### PR TITLE
Added Finnish Tests

### PR DESCRIPTION
**Pull request by bungle**
This is the first try of the Finnish tests to Sugar. Do you see any problems in it? Missing tests? Tests that you like to have?

### CODE REVIEW

**Comment by andrewplummer** [comment]
This is excellent! Thank you so much!

One more small request... If there are differences in case for numbers beyond "1" and "1+" I would like to add tests for all units with that number. For example:

```
test(testCreateDate('1 hour ago',    'en'), '1 tunti sitten');
test(testCreateDate('5 hours ago',   'en'), '5 tuntia sitten');
```

If `2 hours ago` is NOT `2 tuntia sitten`, then lets add tests for all the units for that number to very clearly assert the difference from English. Also for any other numbers that are irregular if possible!

One other thing to note is that although you have this under the "relative" tests:

```
test(testCreateDate('an hour from now',   'en'), 'tunnin päästä');
test(testCreateDate('1 hour from now',    'en'), '1 tunnin päästä');
```

This cannot both work simultaneously. Sugar will understand both `an hour ago` and `1 hour ago` for date creation, however `relative` is a date formatting method and must follow a single format. I would like to assert this to be `1 tunnin päästä` if at all possible. The reason is that this method is purposely intended to be precise. For custom formatting like `about 1 minute ago`, you can pass a function to both the `relative` and `format` methods for customizability, however this should be considered application-logic not part of Sugar, so I would like to follow a simple format.

**Comment by andrewplummer** [comment]
Just in case it's confusing, I should say that my first example is testing `Date.create` (input -- around line 50 in the tests), and the second example is testing `Date#relative` (formatting -- around line 112 in the tests).

**Comment by bungle** [comment]
> If 2 hours ago is NOT 2 tuntia sitten

They are the same.

I will remove those tests without number like "tunnin päästä".

**Comment by bungle** [comment]
In 'create' test we have lines like:

```js
dateEqual(testCreateDate('vuosi sitten'), getRelativeDate(-1), 'one year ago');
dateEqual(testCreateDate('yksi vuosi sitten'), getRelativeDate(-1), 'one year ago');
```

What about other numbers than 1? We have these:

````
0 = nolla
1 = yksi
2 = kaksi
3 = kolme
4 = neljä
5 = viisi
6 = kuusi
7 = seitsemän
8 = kahdeksan
9 = yhdenkäsän
10 = kymmenen
11 - 19 = (1-9)toista e.g. yksitoista, yhdeksäntoista
20,30,40 = (2-9)kymmentä e.g. kaksikymmentä, kolmekymmentä
21,31 = (2-9)kymmentä(1-9) e.g. kaksikymmentäyksi, kaksikymmentäkaksi
100 = sata
200,300 = (2-9)sataa e.g. kaksisataa, yhdeksänsataa
101 = satayksi (see the rules above)
110 = satakymmenen (see the rules above)
111 = satayksitoista (see the rules above)
120 = satakaksikymmentä (see the rules above)
1000 = tuhat, so 1001 = tuhatyksi, 1345 = tuhatkolmesataaneljäkymmentäviisi (follows the same rules as above, words just get longer)
10000 = kymmenentuhatta, 14569 = neljätoistatuhattaviisisataakuusikymmentäyhdeksän
But we never write such number as you can see they are quite horrible, so we use just numbers there, but bigger numbers like
100000 = satatuhatta
1000000 = miljoona
can be seen written
1459293 = miljoonaneljäsataaviisikymmentäyhdeksäntuhattakaksisataayhdeksänkymmentäkolme
=> miljoona_neljä_sataa_viisi_kymmentä_yhdeksän_tuhatta_kaksi_sataa_yhdeksän_kymmentä_kolme => 1000000_4_100_5_10_9_1000_2_100_9_10_3
```

Other thing is that there are test like:

````
dateEqual(testCreateDate('toissapäivänä'), run(getRelativeDate(null, null, -2), 'reset'), 'day before yesterday');
```

Shoud we have others as well, like (not like the above, the following are not written together):

"toissa viikkona" (week), "toissa kuussa" (month), "toissa vuonna" (year)

For futures like "the week after next" we don't have nice versions, so we tend to say just "kahden viikon päästä".

Also I'm not sure if Sugar should have real short date format as well, like:
"22.12.2014" (that is really common form we use here).

**Comment by andrewplummer** [comment]
Well, even for English only the words `one` up to `ten` are supported. Everything beyond that is digits, so I think maybe we should use the same standard here.

> Shoud we have others as well, like

Yes, if possible I think having tests for that would be better...

> Also I'm not sure if Sugar should have real short date format

Do you think you can say that it's the "most common" short date format? If so then it should probably be the standard for "short" (have a look at `lib/locales/fi.js`).

**Comment by bungle** [comment]
> English only the words one up to ten are supported... use the same standard here

Ok. I will make the tests.

> Do you think you can say that it's the "most common" short date format?

I think yes. But more broadly this applies to other languages as well. So all the languages are quite wrong, or we need more formats.  In most languages we have "full" that shows also time, and short version is just without time, but usually otherwise the same.

**Comment by bungle** [comment]
This is what my OSX shows:
screen shot 2015-09-28 at 14 28 13

**Comment by andrewplummer** [comment]
Hm... I think the format it generally follows now is:

short: date only
long: date and time
full: date with weekday and time.

However the formats change I think it's important that they follow the same definitions like this so that you can have a general expectation of what will be output. Beyond that it should be considered custom.

**Pull request merged**
