### PR TITLE
hu (magyar - Hungarian) locale

### PR DESCRIPTION
**Pull request by ovari**
1. Abbreviations end with a dot (.), eg `jan.` not `jan`. Is it correct to use `\\.?`
1. Is the code case-sensitive or case-insensitive?
1. The first day of the week is `Monday` not `Sunday`. Does this matter?

Thank you

https://github.com/andrewplummer/Sugar/issues/658

### CODE REVIEW

**Comment by ovari** [comment]
@jikamens do you know how this merge request can be accepted? Thank you

**Comment by jikamens** [comment]
> @jikamens do you know how this merge request can be accepted? Thank you

Nope, this is all @andrewplummer's department.

**Comment by urbalazs** [comment]
@andrewplummer can you please take a look at this pull request? I'm also interested in this topic. It would be great if the Hungarian locale is part of this project. Thanks!

**Comment by ovari** [comment]
@andrewplummer can you please merge this pull require or advise what you would like done so that it can be merged. Thank you

**Comment by ovari** [comment]
@andrewplummer can you please merge this? If not, please advise so the the fork can be deleted.

@urbalazs did you want to copy this contribution and send a merge request do this fork can be deleted?

Thank you

**Comment by ovari** [comment]
Closed as seems not wanted. Thank you

**Pull request closed without merging**
