### PR TITLE
Add function iSlice (inverted slice)

### PR DESCRIPTION
**Pull request by joakim5937x**
This will add the function iSlice which is a inverted slice function. Taken from my node [module](https://www.npmjs.com/package/inverse-slice).

Inverted slice is used when you know a range elements in a array you don´t want. Otherwise it works similar to slice.

### CODE REVIEW

**Comment by joakim5937x** [comment]
Oh, the CI system does not build the library? Do you need to include "compiled" files in the commit? That seems like bad practice?

**Comment by andrewplummer** [comment]
This method is essentially identical to Sugar's [removeAt](https://sugarjs.com/docs/#/Array/removeAt) method, with the exception that "remove" methods affect the array whereas this method is non-destructive. Although it's very simple to clone the array and do this, I can see a possible need if you're working with arrays extensively, however if I were to add this it would probably be under the name "excludeAt" to keep parity with the naming structure ("exclude" is non destructive and "at" indicates that it is operating with indexes as input).

At any rate, if you would prefer to see your method untouched and with your naming, then this seems like a good chance to try out Sugar's new ability to allow [plugins](https://github.com/andrewplummer/Sugar#defining-methods). I have that small documentation up for now. I am planning on adding a forkable boilerplate repo for Sugar plugins, so I'll leave this issue open until that's done as well!

**Comment by andrewplummer** [comment]
Hi, I've added the boilerplate repo [here](https://github.com/andrewplummer/sugar-plugin-boilerplate). If you choose to use it you'll be the first one, so any feedback is appreciated!

**Comment by joakim5937x** [comment]
@andrewplummer nice man, will check it out! 👍

**Comment by andrewplummer** [comment]
Closing this one for now.

**Pull request closed without merging**
