### PR TITLE
Use '%20' instead of '+' to encode a space.

### PR DESCRIPTION
**Pull request by mgiuffrida**
While [application/x-www-form-urlencoded](http://www.w3.org/TR/html5/forms.html#application/x-www-form-urlencoded-encoding-algorithm) encodes a space as `'+'`, `'%20'` is the more common and more universally accepted encoding. For examaple, JavaScript's own `encodeURIComponent` uses `'%20'`. Similarly, `decodeURIComponent` will properly decode `'%20'` into a space but does not expand `'+'`.

### CODE REVIEW

**Comment by pepkin88** [comment]
I think it might be not recompiling for other changes, and because of this, tests pass, because tests test unchanged library.

**Comment by andrewplummer** [comment]
Hmm, well although `%20` is for URLs in general, this particular method is only concerned with the query string, so not only does application/x-www-form-urlencoded apply, but also RFC2396 (source: http://stackoverflow.com/questions/1211229/in-a-url-should-spaces-be-encoded-using-20-or).

In this sense it can probably be argued that the behavior of `decodeURIComponent` is incorrect.

That said, Sugar exists to provide shortcut patterns for using Javascript as-is, not second-guess it, and I think you're correct here in that doing this is unexpected from someone that knows JS (just looking at that `replace` method is freaking me out... it really shouldn't be there).

However, since both are accepted I think there should probably be an option to replace the `+` character as well.

Most likely this would have to be a third argument to `toQueryString`, although I cringe at going beyond 2 arguments.

Will merge this and figure out that plus the build problem a bit later.

Also really sorry for the long delay.

**Comment by andrewplummer** [comment]
Also `fromQueryString` should have this option as well.

**Comment by mgiuffrida** [comment]
I'm starting to think this patch should not be merged.

AFAICT, RFC2396 does not specify that the query part must be escaped, or that the "+" sign must be used to escape a space (in fact, it only says that "%20" represents the escaped encoding for a space).

OTOH, [W3C does specify](http://www.w3.org/TR/REC-html40/interact/forms.html#idx-form-12) that query strings should use [application/x-www-form-urlencoded](http://www.w3.org/TR/REC-html40/interact/forms.html#didx-applicationx-www-form-urlencoded).

It doesn't seem like encodeURIComponent is actually intended for query strings. Therefore I believe that `toQueryString` is working as intended.

Furthermore, I agree it looks ugly, but [MDN actually suggests](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/encodeURIComponent) using the `replace` method exactly as is done here.

**Comment by andrewplummer** [comment]
Yes, looking at it more the RFCs seem quite complicated. "+" is reserved, but that doesn't necessarily mean much. I was looking at the same MDN article you were.

To be honest, though, I feel like you're actually correct about this... It *should* be intended to not do anything unintended from a Javascript perspective. Although "+" is valid under application/x-www-form-urlencoded, that doesn't necessarily mean that a server could handle it. In that case only option the user would have would be to do another `replace` on the resulting string, which I really don't like...

Thoughts?

**Comment by onlyurei** [comment]
+1 on this proposal by @mgiuffrida, see rationale in #483.

**Comment by crdeutsch** [comment]
This is still open?

The asymmetrical treatment mentioned in #483 is a deal breaker for using these helpers.

What's the rationale for keeping the +?

**Comment by andrewplummer** [comment]
Read the above. Rationales for both sides have been listed quite thoroughly.

**Comment by crdeutsch** [comment]
I guess I don't see a rationale that comes close to trumping the issue that you should get the same thing out that you put in?

I have a single page app.
The user enters a string into a search box "hello world". 
That goes into the Url as a query string.
That triggers React to re-render and the search box changes to "hello+world"

Here's a work around for people that don't want to fork and maintain their own repo just for this
https://gist.github.com/crdeutsch/bfac8f8ccd1c678e30ed

**Comment by andrewplummer** [comment]
Yep, so that's where we're at. Symmetry is a good thing.

**Comment by mgiuffrida** [comment]
So the main argument against this patch boils down to this: Browsers encode spaces in form data as + when submitting forms whose method is "GET" and whose action is a URL. So some query strings are created by substituting + for spaces, and in such a query string an unescaped + encodes a space.

That's not sufficient cause to change the behavior of encodeURI, which chooses to encode spaces as %20. A space in a query string *can* be encoded as a + but JavaScript is consistent in converting spaces to %20 both before and after the ? in a URI.

Between the behavior of encodeURIComponent/decodeURIComponent and the symmetry argument, I'd like to see this patch landed. Consumers should not rely on toQueryString to encode spaces as +, nor on fromQueryString to decode data encoded with the application/x-www-form-urlencoded type.

**Comment by andrewplummer** [comment]
Hi. Ok this has finally been [merged in](https://github.com/andrewplummer/Sugar/commit/86d4702d11b9a60a2dd49baccf90a4f8a4accd49). Had to patch it due to conflicts, but it's in there! Thanks for this and as always sorry for the delay...

**Pull request closed without merging**
